#!/usr/bin/env python3

import rospy
from flask import Flask, render_template, send_from_directory
import threading
import sys
import signal
from werkzeug.serving import make_server

port = 7777
host = "0.0.0.0"


class ServerThread(threading.Thread):

    def __init__(self, app, host_ip, host_port):
        threading.Thread.__init__(self)
        self.server = make_server(host_ip, host_port, app)
        self.ctx = app.app_context()
        self.ctx.push()

    def run(self):
        self.server.serve_forever()

    def shutdown(self):
        self.server.shutdown()


if __name__ == '__main__':

    def signal_handler(signal, frame):
        server.shutdown()
        rospy.signal_shutdown("end")
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)

    try:
    # if True:

        rospy.init_node('webnode', anonymous=True)
        # app = Flask(__name__, static_url_path='/assets')
        app = Flask(__name__,
                    static_url_path='/assets',
                    static_folder='/home/vitulus/catkin_ws/src/vitulus/vitulus_webui/nodes/templates/assets',
                    template_folder='/home/vitulus/catkin_ws/src/vitulus/vitulus_webui/nodes/templates')

        @app.route('/manifest.json')
        def manifest():
            return send_from_directory('/home/vitulus/catkin_ws/src/vitulus/vitulus_webui/nodes/templates', 'manifest.json')

        @app.route("/map_edit")
        def map_edit():
            return render_template('map_edit.html', ros_ip=host)

        @app.route("/")
        def nav():
            return render_template('map_view.html', ros_ip=host)

        @app.route("/imu_calibration")
        def mob_imu_calibration():
            return render_template('imu_calibration.html', ros_ip=host)

        server = ServerThread(app, host, port)
        server.start()
        rospy.loginfo("Initialising webnode node...")
        rospy.loginfo("http://{}:{}".format(host, port))
        rospy.spin()

    except rospy.ROSInterruptException:
        print("Webnode doesn't start!!!!!")



